services:
  riprobot-backend:
    build: 
      context: ./backend
    container_name: riprobot_core
    restart: unless-stopped
    devices:
      - "/dev/sr0:/dev/sr0"      # Reicht das CD-Laufwerk an den Container durch
    ports:
      - "8000:8000"              # Port für das FastAPI Web-Interface
    volumes:
      - ./backend:/app              # Live-Code-Sync für die Entwicklung
      - /media/usb:/output:rshared  # rshared erlaubt Hot-Plugging im laufenden Container
    environment:
      - TZ=Europe/Berlin
      - PYTHONUNBUFFERED=1